doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: '/^(?!departures|flight_information)/'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Module\Dessertation\Domain\FlightInformation:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Module/Dessertation/Infrostructure/Repository/Doctrine/Mapping/FlightInformation'
                prefix: 'App\Module\Dessertation\Domain\FlightInformation'
                alias: App\Module\Dessertation\Domain\FlightInformation
