sylius_fixtures:
    suites:
        departures:
            fixtures:
                departures: ~
            listeners:
                departures_purger: ~
        flight_information:
            fixtures:
                flight_information: ~
            listeners:
                flight_information_purger: ~