controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

dessertation_http:
    resource: ../../src/Module/Dessertation/Infrastructure/Http/Controller/
    type: annotation